name: create_user
on:
  push:
    branches:
    - main
    paths:
      - 'roles/add_user/files/users/**/id_rsa.pub'
      
permissions: 
      id-token: write
      pull-requests: write
      
jobs:
  createUser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
      
      - name: Check diff
        id: diff
        uses: technote-space/get-diff-action@v4.0.2
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PATTERNS: |
            'roles/add_user/files/users/**/id_rsa.pub'     

      - name: Zip entire repository
        if: steps.diff.outputs.diff
        run: zip -r ${{ github.sha }}.zip ./ -x "*.git*"

      - name: Configure AWS Credentials
        if: steps.diff.outputs.diff
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::166313796795:role/test-gha

      - name: Put S3
        run: |
          export REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          aws s3 cp ${{ github.sha }}.zip s3://miyashita-ansible/$REPOSITORY/${{ github.ref_name }}/
          
      - name: Get username
        run: |
          for path in ${{ env.GIT_DIFF }}
          do
            user=$(echo $path | cut -d'/' -f 4)
            echo ${{ env.GIT_DIFF }}
            echo $user
            
            aws ssm send-command \
            --document-name "AWS-ApplyAnsiblePlaybooks" \
            --document-version "1" \
            --targets '[{"Key":"InstanceIds","Values":["i-050e7f95b5e8ecf89"]}]' \
            --parameters '{"SourceType":["S3"],"SourceInfo":["{\"path\": \"https://miyashita-ansible.s3.ap-northeast-1.amazonaws.com/ansible/main/${{ github.sha }}\"}"],"InstallDependencies":["True"],"PlaybookFile":["playbooks/add_user.yml"],"ExtraVariables":["username=$user"],"Check":["False"],"Verbose":["-v"],"TimeoutSeconds":["3600"]}' \
            --timeout-seconds 600 \
            --max-concurrency "50" \
            --max-errors "0" \
            --region ap-northeast-1
          done

      
